on:
  push:
    branches:
      - "**"

name: Publish the page
jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          extended: true

      - name: Build
        run: hugo --minify

      - name: Install rclone
        shell: bash
        run: sudo apt install rclone -y

      - name: Configure remote
        shell: bash
        run: |
          rclone config create remote s3 \
            provider=Other \
            endpoint=${{ secrets.B2_ENDPOINT }} \
            access_key_id=${{ secrets.B2_ACCESS_KEY_ID }} \
              secret_access_key=${{ secrets.B2_SECRET_ACCESS_KEY }}

      - name: Copy the files
        shell: bash
        run: rclone copy public remote:${{ secrets.B2_BUCKET_NAME }}