on:
  push:
    branches:
      - "**"

name: Publish the page
jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          extended: true

      - name: Build
        run: hugo --minify

      - name: Install rclone
        shell: bash
        run: sudo apt install rclone -y

      - name: Assemble rclone config
        run: |
          mkdir -p ~/.config/rclone
          echo "[remote]" > ~/.config/rclone/rclone.conf
          echo "type = b2" >> ~/.config/rclone/rclone.conf
          echo "account = ${{ secrets.B2_ACCESS_KEY_ID }}" >> ~/.config/rclone/rclone.conf
          echo "key = ${{ secrets.B2_SECRET_ACCESS_KEY }}" >> ~/.config/rclone/rclone.conf
          echo "hard_delete = true" >> ~/.config/rclone/rclone.conf
        env:
          B2_ACCESS_KEY_ID: ${{ secrets.B2_ACCESS_KEY_ID }}
          B2_SECRET_ACCESS_KEY: ${{ secrets.B2_SECRET_ACCESS_KEY }}
          B2_ENDPOINT: ${{ secrets.B2_ENDPOINT }}

      - name: Copy the files
        shell: bash
        run: rclone copy public remote:${{ secrets.B2_BUCKET_NAME }}